Repository flaticols/tagger, pull requests merged in 2022-12, with the labels that each got.

#29 Added some logging output
  dist/main/index.js
Labels: Patch

#30 Update README.md
  README.md
Labels: minor

#31 Update repo.ts
  src/repo.ts
Labels: minor

#32 Update README.md
  README.md
Labels: minor

#33 Update index.js
  dist/main/index.js
Labels: Patch

#35 Update version in README
  README.md
Labels: minor

#36 Fix gh to github
  action.yml
Labels: minor

#37 Fixed Dockerfile
  go.mod
  go.sum
  vendor/modules.txt
Labels: Major

#38 Fixed Dockerfile
  Dockerfile
Labels: Major

#39 Fixed Dockerfile
  Dockerfile
Labels: Major

#41 Handle an error
  gh/pr.go
Labels: Major

#42 Fix/get pr labels
  .gitignore
  gh/pr.go
Labels: Major

#43 Log owner PR and repository
  commands/do.go
  gh/pr.go
  main.go
Labels: Major

#44 Log owner PR and repository
  gh/pr.go
Labels: Major

#45 Log owner PR and repository
  gh/pr.go
Labels: Major

#46 Log owner PR and repository
  gh/pr.go
Labels: Major

#47 Added tests
  gh/pr.go
  gh/pr_test.go
  go.mod
  go.sum
  vendor/github.com/google/go-github/v48/AUTHORS
  vendor/github.com/google/go-github/v48/github/actions_workflow_jobs.go
  vendor/github.com/google/go-github/v48/github/github-accessors.go
  vendor/github.com/google/go-github/v48/github/github.go
  vendor/github.com/google/go-github/v48/github/issues.go
  vendor/github.com/google/go-github/v48/github/issues_timeline.go
  vendor/github.com/google/go-github/v48/github/orgs_packages.go
  vendor/github.com/google/go-github/v48/github/repos.go
  vendor/github.com/google/go-github/v48/github/repos_actions_access.go
  vendor/github.com/google/go-github/v48/github/repos_forks.go
  vendor/github.com/google/go-github/v48/github/repos_releases.go
  vendor/modules.txt
Labels: minor

#48 Normalize repo name
  gh/pr.go
  inputs/input.go
Labels: minor

#49 Rename `do` to `create`
  Dockerfile
  README.md
  commands/create.go
  main.go
Labels: minor
